# .github/workflows/build-executable.yml
# GitHub Action per creare automaticamente un eseguibile
name: Build Executable Fixed

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  NODE_VERSION: '20.19.0'

jobs:
  build-backend:
    name: Build Backend Executable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Verify project structure
        run: |
          echo "Project structure:"
          find . -name "pom.xml" -type f
          ls -la backend/sweng/

      - name: Build Spring Boot JAR
        working-directory: ./backend/sweng
        run: |
          echo "Building executable JAR..."
          mvn clean package -DskipTests
          echo "Build completed, checking target directory:"
          ls -la target/

      - name: Rename JAR file
        working-directory: ./backend/sweng/target
        run: |
          echo "Available JAR files:"
          ls -la *.jar
          # Trova il JAR principale (non quello con -sources o -javadoc)
          JAR_FILE=$(ls *.jar | grep -v sources | grep -v javadoc | head -1)
          echo "Using JAR: $JAR_FILE"
          cp "$JAR_FILE" nota-bene-backend-executable.jar

      - name: Upload Backend Executable
        uses: actions/upload-artifact@v4
        with:
          name: nota-bene-backend-jar
          path: backend/sweng/target/nota-bene-backend-executable.jar
          retention-days: 30

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify frontend structure
        run: |
          echo "Frontend structure:"
          find . -name "package.json" -type f
          if [ -f "frontend/package.json" ]; then
            echo "package.json found in frontend/"
            ls -la frontend/
          else
            echo "ERROR: package.json not found in frontend/"
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          echo "Installing npm dependencies..."
          npm ci

      - name: Check Angular CLI and scripts
        working-directory: ./frontend
        run: |
          echo "Available npm scripts:"
          npm run
          echo ""
          echo "Checking Angular version:"
          npx ng version || echo "Angular CLI not found locally"
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular application
        working-directory: ./frontend
        run: |
          echo "Building Angular production build..."
          ng build --configuration=production

      - name: Create Frontend Archive
        working-directory: ./frontend
        run: |
          if [ -d "dist" ]; then
            echo "Contents of dist directory:"
            ls -la dist/
          
            # Cerca la directory corretta
            if [ -d "dist/frontend" ]; then
              cd dist/frontend
              tar -czf ../../nota-bene-frontend-dist.tar.gz *
            elif [ "$(ls -A dist/)" ]; then
              cd dist
              tar -czf ../nota-bene-frontend-dist.tar.gz *
            else
              echo "ERROR: dist directory is empty"
              exit 1
            fi
          else
            echo "ERROR: dist directory not found"
            exit 1
          fi

      - name: Upload Frontend Build
        uses: actions/upload-artifact@v4
        with:
          name: nota-bene-frontend-dist
          path: frontend/nota-bene-frontend-dist.tar.gz

          retention-days: 30

  # Job combinato per creare una release se è un tag
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
  #  if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: nota-bene-backend-jar

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: nota-bene-frontend-dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nota-bene-backend-executable.jar
            nota-bene-frontend-dist.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
