name: Java Lint with Checkstyle

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Run Checkstyle with Maven
      working-directory: backend/sweng
      run: mvn checkstyle:check
